#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeiBo.Synchro.Core
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ZM_Dev")]
	public partial class TDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertAA_ComputationUnit(AA_ComputationUnit instance);
    partial void UpdateAA_ComputationUnit(AA_ComputationUnit instance);
    partial void DeleteAA_ComputationUnit(AA_ComputationUnit instance);
    partial void InsertAA_Customer(AA_Customer instance);
    partial void UpdateAA_Customer(AA_Customer instance);
    partial void DeleteAA_Customer(AA_Customer instance);
    #endregion
		
		public TDBDataContext() : 
				base(global::FeiBo.Synchro.Core.Properties.Settings.Default.zzpConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<v_zzp_Get_AA_ComputationUnit> v_zzp_Get_AA_ComputationUnit
		{
			get
			{
				return this.GetTable<v_zzp_Get_AA_ComputationUnit>();
			}
		}
		
		public System.Data.Linq.Table<AA_ComputationUnit> AA_ComputationUnit
		{
			get
			{
				return this.GetTable<AA_ComputationUnit>();
			}
		}
		
		public System.Data.Linq.Table<AA_Customer> AA_Customer
		{
			get
			{
				return this.GetTable<AA_Customer>();
			}
		}
		
		public System.Data.Linq.Table<v_zzp_Get_AA_Customer> v_zzp_Get_AA_Customer
		{
			get
			{
				return this.GetTable<v_zzp_Get_AA_Customer>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_zzp_load_AA_ComputationUnit")]
		public int p_zzp_load_AA_ComputationUnit()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_zzp_log_tools")]
		public int p_zzp_log_tools([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string cMethod, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> errcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string errmsg)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cType, cMethod, errcode, errmsg);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_zzp_log_api")]
		public int p_zzp_log_api([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ip, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string cIdentity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string cMethod, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> errcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string errmsg, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string cParams)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ip, cIdentity, cType, cMethod, errcode, errmsg, cParams);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_zzp_load_AA_Customer")]
		public int p_zzp_load_AA_Customer()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_zzp_Get_AA_ComputationUnit")]
	public partial class v_zzp_Get_AA_ComputationUnit
	{
		
		private string _unitName;
		
		private decimal _rate;
		
		private string _en;
		
		private string _zh;
		
		private System.Nullable<long> _ts;
		
		public v_zzp_Get_AA_ComputationUnit()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string unitName
		{
			get
			{
				return this._unitName;
			}
			set
			{
				if ((this._unitName != value))
				{
					this._unitName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="Decimal(28,6) NOT NULL")]
		public decimal rate
		{
			get
			{
				return this._rate;
			}
			set
			{
				if ((this._rate != value))
				{
					this._rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_en", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string en
		{
			get
			{
				return this._en;
			}
			set
			{
				if ((this._en != value))
				{
					this._en = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string zh
		{
			get
			{
				return this._zh;
			}
			set
			{
				if ((this._zh != value))
				{
					this._zh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts", DbType="BigInt")]
		public System.Nullable<long> ts
		{
			get
			{
				return this._ts;
			}
			set
			{
				if ((this._ts != value))
				{
					this._ts = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AA_ComputationUnit")]
	public partial class AA_ComputationUnit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _unitName;
		
		private decimal _rate;
		
		private string _en;
		
		private string _zh;
		
		private System.Nullable<long> _ts;
		
		private int _iStatus;
		
		private bool _bFlag;
		
		private bool _bDel;
		
		private string _errcode;
		
		private string _errmsg;
		
		private System.DateTime _dCreateTime;
		
		private System.Nullable<System.DateTime> _dUpdateTime;
		
		private System.Nullable<System.DateTime> _dPostTime;
		
		private string _cMemo;
		
		private System.Nullable<int> _define1;
		
		private string _define2;
		
		private string _define3;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnunitNameChanging(string value);
    partial void OnunitNameChanged();
    partial void OnrateChanging(decimal value);
    partial void OnrateChanged();
    partial void OnenChanging(string value);
    partial void OnenChanged();
    partial void OnzhChanging(string value);
    partial void OnzhChanged();
    partial void OntsChanging(System.Nullable<long> value);
    partial void OntsChanged();
    partial void OniStatusChanging(int value);
    partial void OniStatusChanged();
    partial void OnbFlagChanging(bool value);
    partial void OnbFlagChanged();
    partial void OnbDelChanging(bool value);
    partial void OnbDelChanged();
    partial void OnerrcodeChanging(string value);
    partial void OnerrcodeChanged();
    partial void OnerrmsgChanging(string value);
    partial void OnerrmsgChanged();
    partial void OndCreateTimeChanging(System.DateTime value);
    partial void OndCreateTimeChanged();
    partial void OndUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OndUpdateTimeChanged();
    partial void OndPostTimeChanging(System.Nullable<System.DateTime> value);
    partial void OndPostTimeChanged();
    partial void OncMemoChanging(string value);
    partial void OncMemoChanged();
    partial void Ondefine1Changing(System.Nullable<int> value);
    partial void Ondefine1Changed();
    partial void Ondefine2Changing(string value);
    partial void Ondefine2Changed();
    partial void Ondefine3Changing(string value);
    partial void Ondefine3Changed();
    #endregion
		
		public AA_ComputationUnit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string unitName
		{
			get
			{
				return this._unitName;
			}
			set
			{
				if ((this._unitName != value))
				{
					this.OnunitNameChanging(value);
					this.SendPropertyChanging();
					this._unitName = value;
					this.SendPropertyChanged("unitName");
					this.OnunitNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="Decimal(28,6) NOT NULL")]
		public decimal rate
		{
			get
			{
				return this._rate;
			}
			set
			{
				if ((this._rate != value))
				{
					this.OnrateChanging(value);
					this.SendPropertyChanging();
					this._rate = value;
					this.SendPropertyChanged("rate");
					this.OnrateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_en", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string en
		{
			get
			{
				return this._en;
			}
			set
			{
				if ((this._en != value))
				{
					this.OnenChanging(value);
					this.SendPropertyChanging();
					this._en = value;
					this.SendPropertyChanged("en");
					this.OnenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string zh
		{
			get
			{
				return this._zh;
			}
			set
			{
				if ((this._zh != value))
				{
					this.OnzhChanging(value);
					this.SendPropertyChanging();
					this._zh = value;
					this.SendPropertyChanged("zh");
					this.OnzhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts", DbType="BigInt")]
		public System.Nullable<long> ts
		{
			get
			{
				return this._ts;
			}
			set
			{
				if ((this._ts != value))
				{
					this.OntsChanging(value);
					this.SendPropertyChanging();
					this._ts = value;
					this.SendPropertyChanged("ts");
					this.OntsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iStatus", DbType="Int NOT NULL")]
		public int iStatus
		{
			get
			{
				return this._iStatus;
			}
			set
			{
				if ((this._iStatus != value))
				{
					this.OniStatusChanging(value);
					this.SendPropertyChanging();
					this._iStatus = value;
					this.SendPropertyChanged("iStatus");
					this.OniStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bFlag", DbType="Bit NOT NULL")]
		public bool bFlag
		{
			get
			{
				return this._bFlag;
			}
			set
			{
				if ((this._bFlag != value))
				{
					this.OnbFlagChanging(value);
					this.SendPropertyChanging();
					this._bFlag = value;
					this.SendPropertyChanged("bFlag");
					this.OnbFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bDel", DbType="Bit NOT NULL")]
		public bool bDel
		{
			get
			{
				return this._bDel;
			}
			set
			{
				if ((this._bDel != value))
				{
					this.OnbDelChanging(value);
					this.SendPropertyChanging();
					this._bDel = value;
					this.SendPropertyChanged("bDel");
					this.OnbDelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_errcode", DbType="VarChar(50)")]
		public string errcode
		{
			get
			{
				return this._errcode;
			}
			set
			{
				if ((this._errcode != value))
				{
					this.OnerrcodeChanging(value);
					this.SendPropertyChanging();
					this._errcode = value;
					this.SendPropertyChanged("errcode");
					this.OnerrcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_errmsg", DbType="NVarChar(MAX)")]
		public string errmsg
		{
			get
			{
				return this._errmsg;
			}
			set
			{
				if ((this._errmsg != value))
				{
					this.OnerrmsgChanging(value);
					this.SendPropertyChanging();
					this._errmsg = value;
					this.SendPropertyChanged("errmsg");
					this.OnerrmsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dCreateTime", DbType="DateTime NOT NULL")]
		public System.DateTime dCreateTime
		{
			get
			{
				return this._dCreateTime;
			}
			set
			{
				if ((this._dCreateTime != value))
				{
					this.OndCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._dCreateTime = value;
					this.SendPropertyChanged("dCreateTime");
					this.OndCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dUpdateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dUpdateTime
		{
			get
			{
				return this._dUpdateTime;
			}
			set
			{
				if ((this._dUpdateTime != value))
				{
					this.OndUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._dUpdateTime = value;
					this.SendPropertyChanged("dUpdateTime");
					this.OndUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dPostTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dPostTime
		{
			get
			{
				return this._dPostTime;
			}
			set
			{
				if ((this._dPostTime != value))
				{
					this.OndPostTimeChanging(value);
					this.SendPropertyChanging();
					this._dPostTime = value;
					this.SendPropertyChanged("dPostTime");
					this.OndPostTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cMemo", DbType="NVarChar(MAX)")]
		public string cMemo
		{
			get
			{
				return this._cMemo;
			}
			set
			{
				if ((this._cMemo != value))
				{
					this.OncMemoChanging(value);
					this.SendPropertyChanging();
					this._cMemo = value;
					this.SendPropertyChanged("cMemo");
					this.OncMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_define1", DbType="Int")]
		public System.Nullable<int> define1
		{
			get
			{
				return this._define1;
			}
			set
			{
				if ((this._define1 != value))
				{
					this.Ondefine1Changing(value);
					this.SendPropertyChanging();
					this._define1 = value;
					this.SendPropertyChanged("define1");
					this.Ondefine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_define2", DbType="VarChar(MAX)")]
		public string define2
		{
			get
			{
				return this._define2;
			}
			set
			{
				if ((this._define2 != value))
				{
					this.Ondefine2Changing(value);
					this.SendPropertyChanging();
					this._define2 = value;
					this.SendPropertyChanged("define2");
					this.Ondefine2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_define3", DbType="NVarChar(MAX)")]
		public string define3
		{
			get
			{
				return this._define3;
			}
			set
			{
				if ((this._define3 != value))
				{
					this.Ondefine3Changing(value);
					this.SendPropertyChanging();
					this._define3 = value;
					this.SendPropertyChanged("define3");
					this.Ondefine3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AA_Customer")]
	public partial class AA_Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _customerCode;
		
		private string _customerName;
		
		private string _address;
		
		private string _contactor;
		
		private string _phone;
		
		private string _description;
		
		private string _en;
		
		private string _zh;
		
		private System.Nullable<long> _ts;
		
		private int _iStatus;
		
		private bool _bFlag;
		
		private bool _bDel;
		
		private string _errcode;
		
		private string _errmsg;
		
		private System.DateTime _dCreateTime;
		
		private System.Nullable<System.DateTime> _dUpdateTime;
		
		private System.Nullable<System.DateTime> _dPostTime;
		
		private string _cMemo;
		
		private System.Nullable<int> _define1;
		
		private string _define2;
		
		private string _define3;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncustomerCodeChanging(string value);
    partial void OncustomerCodeChanged();
    partial void OncustomerNameChanging(string value);
    partial void OncustomerNameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncontactorChanging(string value);
    partial void OncontactorChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnenChanging(string value);
    partial void OnenChanged();
    partial void OnzhChanging(string value);
    partial void OnzhChanged();
    partial void OntsChanging(System.Nullable<long> value);
    partial void OntsChanged();
    partial void OniStatusChanging(int value);
    partial void OniStatusChanged();
    partial void OnbFlagChanging(bool value);
    partial void OnbFlagChanged();
    partial void OnbDelChanging(bool value);
    partial void OnbDelChanged();
    partial void OnerrcodeChanging(string value);
    partial void OnerrcodeChanged();
    partial void OnerrmsgChanging(string value);
    partial void OnerrmsgChanged();
    partial void OndCreateTimeChanging(System.DateTime value);
    partial void OndCreateTimeChanged();
    partial void OndUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OndUpdateTimeChanged();
    partial void OndPostTimeChanging(System.Nullable<System.DateTime> value);
    partial void OndPostTimeChanged();
    partial void OncMemoChanging(string value);
    partial void OncMemoChanged();
    partial void Ondefine1Changing(System.Nullable<int> value);
    partial void Ondefine1Changed();
    partial void Ondefine2Changing(string value);
    partial void Ondefine2Changed();
    partial void Ondefine3Changing(string value);
    partial void Ondefine3Changed();
    #endregion
		
		public AA_Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string customerCode
		{
			get
			{
				return this._customerCode;
			}
			set
			{
				if ((this._customerCode != value))
				{
					this.OncustomerCodeChanging(value);
					this.SendPropertyChanging();
					this._customerCode = value;
					this.SendPropertyChanged("customerCode");
					this.OncustomerCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerName", DbType="NVarChar(98)")]
		public string customerName
		{
			get
			{
				return this._customerName;
			}
			set
			{
				if ((this._customerName != value))
				{
					this.OncustomerNameChanging(value);
					this.SendPropertyChanging();
					this._customerName = value;
					this.SendPropertyChanged("customerName");
					this.OncustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(255)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactor", DbType="NVarChar(50)")]
		public string contactor
		{
			get
			{
				return this._contactor;
			}
			set
			{
				if ((this._contactor != value))
				{
					this.OncontactorChanging(value);
					this.SendPropertyChanging();
					this._contactor = value;
					this.SendPropertyChanged("contactor");
					this.OncontactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(100)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_en", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string en
		{
			get
			{
				return this._en;
			}
			set
			{
				if ((this._en != value))
				{
					this.OnenChanging(value);
					this.SendPropertyChanging();
					this._en = value;
					this.SendPropertyChanged("en");
					this.OnenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zh", DbType="NVarChar(255)")]
		public string zh
		{
			get
			{
				return this._zh;
			}
			set
			{
				if ((this._zh != value))
				{
					this.OnzhChanging(value);
					this.SendPropertyChanging();
					this._zh = value;
					this.SendPropertyChanged("zh");
					this.OnzhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts", DbType="BigInt")]
		public System.Nullable<long> ts
		{
			get
			{
				return this._ts;
			}
			set
			{
				if ((this._ts != value))
				{
					this.OntsChanging(value);
					this.SendPropertyChanging();
					this._ts = value;
					this.SendPropertyChanged("ts");
					this.OntsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iStatus", DbType="Int NOT NULL")]
		public int iStatus
		{
			get
			{
				return this._iStatus;
			}
			set
			{
				if ((this._iStatus != value))
				{
					this.OniStatusChanging(value);
					this.SendPropertyChanging();
					this._iStatus = value;
					this.SendPropertyChanged("iStatus");
					this.OniStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bFlag", DbType="Bit NOT NULL")]
		public bool bFlag
		{
			get
			{
				return this._bFlag;
			}
			set
			{
				if ((this._bFlag != value))
				{
					this.OnbFlagChanging(value);
					this.SendPropertyChanging();
					this._bFlag = value;
					this.SendPropertyChanged("bFlag");
					this.OnbFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bDel", DbType="Bit NOT NULL")]
		public bool bDel
		{
			get
			{
				return this._bDel;
			}
			set
			{
				if ((this._bDel != value))
				{
					this.OnbDelChanging(value);
					this.SendPropertyChanging();
					this._bDel = value;
					this.SendPropertyChanged("bDel");
					this.OnbDelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_errcode", DbType="VarChar(50)")]
		public string errcode
		{
			get
			{
				return this._errcode;
			}
			set
			{
				if ((this._errcode != value))
				{
					this.OnerrcodeChanging(value);
					this.SendPropertyChanging();
					this._errcode = value;
					this.SendPropertyChanged("errcode");
					this.OnerrcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_errmsg", DbType="NVarChar(MAX)")]
		public string errmsg
		{
			get
			{
				return this._errmsg;
			}
			set
			{
				if ((this._errmsg != value))
				{
					this.OnerrmsgChanging(value);
					this.SendPropertyChanging();
					this._errmsg = value;
					this.SendPropertyChanged("errmsg");
					this.OnerrmsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dCreateTime", DbType="DateTime NOT NULL")]
		public System.DateTime dCreateTime
		{
			get
			{
				return this._dCreateTime;
			}
			set
			{
				if ((this._dCreateTime != value))
				{
					this.OndCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._dCreateTime = value;
					this.SendPropertyChanged("dCreateTime");
					this.OndCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dUpdateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dUpdateTime
		{
			get
			{
				return this._dUpdateTime;
			}
			set
			{
				if ((this._dUpdateTime != value))
				{
					this.OndUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._dUpdateTime = value;
					this.SendPropertyChanged("dUpdateTime");
					this.OndUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dPostTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dPostTime
		{
			get
			{
				return this._dPostTime;
			}
			set
			{
				if ((this._dPostTime != value))
				{
					this.OndPostTimeChanging(value);
					this.SendPropertyChanging();
					this._dPostTime = value;
					this.SendPropertyChanged("dPostTime");
					this.OndPostTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cMemo", DbType="NVarChar(MAX)")]
		public string cMemo
		{
			get
			{
				return this._cMemo;
			}
			set
			{
				if ((this._cMemo != value))
				{
					this.OncMemoChanging(value);
					this.SendPropertyChanging();
					this._cMemo = value;
					this.SendPropertyChanged("cMemo");
					this.OncMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_define1", DbType="Int")]
		public System.Nullable<int> define1
		{
			get
			{
				return this._define1;
			}
			set
			{
				if ((this._define1 != value))
				{
					this.Ondefine1Changing(value);
					this.SendPropertyChanging();
					this._define1 = value;
					this.SendPropertyChanged("define1");
					this.Ondefine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_define2", DbType="VarChar(MAX)")]
		public string define2
		{
			get
			{
				return this._define2;
			}
			set
			{
				if ((this._define2 != value))
				{
					this.Ondefine2Changing(value);
					this.SendPropertyChanging();
					this._define2 = value;
					this.SendPropertyChanged("define2");
					this.Ondefine2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_define3", DbType="NVarChar(MAX)")]
		public string define3
		{
			get
			{
				return this._define3;
			}
			set
			{
				if ((this._define3 != value))
				{
					this.Ondefine3Changing(value);
					this.SendPropertyChanging();
					this._define3 = value;
					this.SendPropertyChanged("define3");
					this.Ondefine3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_zzp_Get_AA_Customer")]
	public partial class v_zzp_Get_AA_Customer
	{
		
		private string _customerCode;
		
		private string _customerName;
		
		private string _address;
		
		private string _contactor;
		
		private string _phone;
		
		private string _description;
		
		private string _en;
		
		private string _zh;
		
		private System.Nullable<long> _ts;
		
		public v_zzp_Get_AA_Customer()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string customerCode
		{
			get
			{
				return this._customerCode;
			}
			set
			{
				if ((this._customerCode != value))
				{
					this._customerCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerName", DbType="NVarChar(98)")]
		public string customerName
		{
			get
			{
				return this._customerName;
			}
			set
			{
				if ((this._customerName != value))
				{
					this._customerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(255)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactor", DbType="NVarChar(50)")]
		public string contactor
		{
			get
			{
				return this._contactor;
			}
			set
			{
				if ((this._contactor != value))
				{
					this._contactor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(100)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_en", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string en
		{
			get
			{
				return this._en;
			}
			set
			{
				if ((this._en != value))
				{
					this._en = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zh", DbType="NVarChar(255)")]
		public string zh
		{
			get
			{
				return this._zh;
			}
			set
			{
				if ((this._zh != value))
				{
					this._zh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts", DbType="BigInt")]
		public System.Nullable<long> ts
		{
			get
			{
				return this._ts;
			}
			set
			{
				if ((this._ts != value))
				{
					this._ts = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
